# don't use container based infrastructure cause we need sudo
sudo: required
language: java
os:
  - linux
jdk:
  - openjdk8
python:
  - "2.7"
cache:
  directories:
  - $HOME/.m2
  - ./node_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
    sauce_connect:
      username: $SAUCE_USERNAME
      access_key: $SAUCE_ACCESS_KEY
before_install:
  - export CXX=g++-4.9
  - export NODE_OPTIONS=--max-old-space-size=4096
  - sudo rm -vf /etc/apt/sources.list.d/*riak*
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update -qq
  - sudo apt-get install cf-cli -y
  - sudo apt-get -y install python-pip python-dev
  - pip install robotframework --user
  - pip install robotframework-extendedselenium2library --user
  - pip install pyyaml --user
  - pip install six --user
# turn off travis default mvn install call and install a recent node version instead
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 9.11.1
  - npm install -g bower
  - npm install -g grunt-cli
# do not install into local maven repo to avoid polluting the cache
script:
  - mvn -Pdev --settings ./buildconfig/settings.xml -B -DrepoToken=$COVERALLS_TOKEN package
  - cf login -u $CI_DEPLOY_USERNAME -p $CI_DEPLOY_PASSWORD -o DZHW -s dev -a https://api.run.pivotal.io
  - cf push -f ./deploy/manifest-dev.yml
  - robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs -v USE_SAUCELABS:TRUE -v BROWSER:chrome --include smoketest --include chromeonly ./src/test/robotframework
  - robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs -v USE_SAUCELABS:TRUE -v BROWSER:firefox --include smoketest ./src/test/robotframework
  - robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs -v USE_SAUCELABS:TRUE -v BROWSER:ie --include smoketest --exclude noslowpoke ./src/test/robotframework
  - robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs -v USE_SAUCELABS:TRUE -v BROWSER:edge --include smoketest --exclude noslowpoke ./src/test/robotframework
after_script:
 - mvn coveralls:report
notifications:
  email:
    recipients:
      - secure: "Rf1Buy3jin0Ge66oyBsjGH6HuW111g9kjt5miW4aSi6Y5jZH5z8E27nDvZrxspMq4oW3j2pvbR1ru/+lEqPmgdtXQs5UxmiSBwMoEQXhMMrZNKzBHgK9MaEMrlx6dXBpwPYhsMqL+ojKmGDgG+X6M9D9SQ/FNQFbTTZWco1YUMlzBUG+eG5iAqsLmJMIn1R3n1VnaOaU5uqdonKfIkmI3uq7vF89oqWvlrHGmXrmahuOie0RwLiyb1cN0pskhszUMe7rmIw+sljS5Ic3JcxgPVWh1Ii5+jdt7GpaMgybMIB5lGQjs9jfftP2QllBqZlAMQLAGmuG44lxgB9AnFdszJqi3NurV+vJG97a9NSWNirKY2Emsb05lqYFeHDE38kqbfyfRX2g2JojdhEymOJoiYRToCFmv2uDvYMslNgpp9BEkQk3xse90uZZ2ropSdwPFMIR4yLhLOaQVl8dmCmtwCun6vEVdmU3GcO82nRuYedkE8midlWbkig6o3lvyaiHTcyk5E9sD6ETTlgxIVnJSLSwKEPi5cVrpU5yXox2duoJVTvxA/MUudtZV3r9Yrar0cT/25FF40RnxR59yWNel/NjR7mLcvWAEQ5g8EAU5mSAWIAjlQr7hZt1dBPQTKA3M2D6LfpSI04vKcf6vXy1mscPHI0Nu6Otti98SzXt5us="
      - secure: "QRwlzcGeh/jZ95gOg22z8+Dxc9lrS+k56Rc/X6/ISiJFAfDmGWJjWYAhSRkL1GMQb+NQgwdOz+MLGuBzcaYxwk1DZE8NV82FDjW2pbBKGAjPxexUZrOzxZ2W+ntOvjlnBOcBVygTT5DdxBf+5gBAB9ibwdvWaDCby1m6wE/LEhVl96njYzvRBhmv8OojHmaLmTxOGn3/McUj+6riIUJufTTTXy35lnbEjNVW+CDrKQt09/FDNJiFuzEkel/DMu8PBQ7jy7SIY/hC7QPe+Qjp+eUxITTfZWAVxnq4t0F9gOLXBN+1FzKISeRac6kfJKCsAPw4DolPnJYhdF2UdeLZfESd6wVu7zwEvtM9YM3pjfQ/sj7Jxg11LLT6eiYwZ50DRJrZSKV4kg/ZtqemSQldREYDP0MY/+dE9h/rLIB8ePMCIasJOzAXPujGNZKZRoN9fJeGqB2NWKeGbXVffNi8rC599hqsj8dAxskuFfZQ240bYSsQNREvFayL/mn7av4EavWb2Gr+1hsGF48sbKWrRmCtfXjEK4ggdx09W/APsSEWgslPwDmeUeK1ygVlJRgh/CVS52WkosKsMCYZetL1n3hXORKCWBx+QCskmcEyQA85tjE66RDOEmvnxOLAGzct7wF3vJFkGsPiwntLL1F0KX3F/h8afuyALkz9cA8T5gI="
