# send this build to the container based infrastructure anymore
sudo: false
language: java
os:
  - linux
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - ./node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
# turn off travis default mvn install call and install a recent node version instead
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 7.4.0
  - npm install -g bower
  - npm install -g grunt-cli
# do not install into local maven repo to avoid polluting the cache
script:
  - mvn -Pdev --settings ./buildconfig/settings.xml -B -DrepoToken=$COVERALLS_TOKEN package cf:push-only
  - ./node_modules/protractor/bin/webdriver-manager update --standalone
  - ./node_modules/protractor/bin/protractor ./src/test/protractor/protractor.conf.js
after_script:
 - mvn coveralls:report
notifications:
  email:
    recipients:
      - secure: "BqE8L9B7JNlQFwPOUGoYEEXM8JclCFLEhystUL3OOxZ69Vl0hLo3/Bz/bL0Jk8HBSpNRCx74ymTEioOHOu+k5PG4MsEfCND5WYhAJXcgw/ak9RYU5VvB/L60FSrfvtZecnrqL2Jz9rpL/nFIy/Q+uWJoNyNcQneO7Fw7D3AAAg4uSAaRHS0jITrCnqreUYV3zUMhoBcYR2vxlJ2hoKOyUJAF1I9jkMvaEs46oyKRlSrbuahSXjAmpjnKMPc6MhVp9wt8mmevWZhBKQ6a4XIH8QfDwF7muSCmZDI1De/MSmJL5kueRC3IDIh7Y5NN+6G6V7E7w4KfpFPkOlMWuFKjevDKMCgWkdFH0pJ+hp0c4/uFozTa+zclkoYrU6xZo3KUBZmt6VUNvp35hZcM35CS7pq4L+7zXx+X3w5hJlMQxuNrSi6W74PGCilMJ+j1p2/PMJ5Zrm6vEnvgm7soNYN90Av+cjGJQjG46a6mDlvmoF5mxQhKPX6NmypLEqxj8DGTN7bL5zvfNknWTp89lC4ByLQU58aEB8fIUSoKFLVhhcqvxwqcwGNkVkFvj6dXQZUGActPedajaUOQNYZBkjMwZiU7D9B/f5CtjD8d81+T49onp6W+9fcz87bMSKuymvnbgyAwyxlyFhb75ynTuSS9GnYOUXI26ixBS+vHdk4qatU="
      - secure: "XN8JhLr9s2st/2Z9ajt+r33QBktLbjAbQvYBUv0kMy3tqMqQhTTEsefBqE9s1CNVSUflARmIg6GIXfGg/WwH7guLE28/MkMw65EZvpp27Rj2eVBCSfbCCH9c3bADf83uIIN6iWSCYmf+RTgEs5ZKQr01a7+XuH064CSzL81sWE/9kwhQ8KCru2CPIR/rNCRguwbUQbQVAgYQ1pwuuvOZYJ0cB3JqHrh2fcirZEymVpl4rTbv3sIHhxMNsFg7U6UAmKDv6VAK3KxMIATyEqavZtPZ+A48OqXuY+LWv0RwtaKQMNB0iBq0+H4MiwN2kV3TTJx7kMjfMp9rtCrsaUKmER7/8O8ECChGsTGWDHH1fwjnO0LZRXKDJBmniJEQqcrtHE0LA0Zma15wOkU7pjHAqEW6Ouf8NGy2V17aZr+sgE56bM9M5Rm5MgdQJ4TS86WRZIlV3qtAq3HpewhVvPjQnZdo+LYC+dPmk1cCPOyVIko6qzinJGUWOcwYhVJBcvqBNbPSd4MdO5OgCQ9R+fx7MC6Sq8hbdK2MSg/sI+O2BQcwuQuyMKpS9ytT1RIKFkZNs6E1TtglNXjGW/i4Zvd7lEst4IztiSpAeVg0+bloOPIoq2MKLJS/61cFxNI2tAPSYGnA9aIhHBZ3z7PPnRJQFqGEOz4x/8R6e1SDwXBB2uQ="
      - secure: "RRVBfro2I2ZJ9T3O6XkBLIZ8sNlS+Ud7mZS7mN7rD1lcyR/2IHqPYvVtJYU/ODps5iAjrf7sJvUqqkdHFlkZQfYS7D8kPiwwDSBzqiezvIWUyp4YvxEKFZD1a33YYpu6xYD1WqWjbOWeJnit6qDAsUYuqlJfcf/rqFaZChGMEXYooDb7Ff33ywnEBreCWrn3f5Jny4Pb6whPvD25CkPrqhi5bQ9YAJN7knwiiG2iDQ2XL5+/YENwFiPV3os1ypuBbOkwK6v4qOAx1Cy3lt3gJNZxKhcZ1nYGR1mC7znHDle/F3JIfqDrmoqT+MleOkogt6xS9OL92nn3OaEBBJpEz8i0cEl6eiOVv8E/drg6Cttqnl1v8sWTBLWH6G53bsK73x2/Zn5s2Y2nzoWigUaP2Yt3C94ER7u5NsrKuHTV4o3eucfdSC1Lj8vlxDqYHF6txGQvxwcmormxCYQZCIfsIgW2eiWy9hYQgW2LiOt4m2bz3oym7ej2dgsM7zJL9PJcmi40LJUyNU8Q7yYh5kyALiJwnLgYp6LzhO4GMfBrTBMZbl4VYGg6zcH+chXTodIw8vh17Hp88wZ5DQHWe1hOg1AuXdWHEho+/eZMXm9RfS4sSxZskvB3EufbkK2dWKzZgSwkbVGYs33Qo2BpYD6INjGt2AfC7kIaIFc5RslmpmU="
      - secure: "gx1x+Q+v921191ljKOLaV7DHkwWt5hRBnb8vGAi0EgaXjGrKtozWXGlUXxaZ8Dpbi20BYkiur/YDHUrpY45ec5UzlKA/IFJyRveJb+aVMIcC5NbipuENiwhL9ggplqGlLGVXUuaKzHIMb1332WEbNJq2ZHf1Gi7o3Jmoz2G6eCOOn9oj77xHbRrBWcjPQXlqC1mnE+Zm7qa9WAR2MDyzO2zmS+9NujL4c8Vi7jTa+ZhxkUSybmuY2XFgeLawWL7L9ZluJpUYfUMjYmnItVS+539rw+o7Q0rETqcw6REaLI0yPgk1T0NzqNYxA3sRl9qXl+Q4D1/2I1N3WIcdGn6aUNlN6FJucmzbVWvRTH/c0gwqu8KmVggiuRbUt4e5AnRgjpf+rKJsHvZk+U+vYXeLAu4Auvyb0DS0UhLFRN6GzcUIA5KH1pXld4B/RHA/7ntYP/fjBuN/W4jZ9YHpgvqkl2oIh9dzD0sMjvAoXlmRquHR/pSWhUujtNMFR8ciC28sxqhUVb2bzYrVOBclSYlT5/mEHClmqHJxg6iHM3gTfXWgPyJxpNmyBDj7nhfjabkcyFwaLLb2Dbi67IoA3FT4Dgne8dY/cjc1tzlySWdSiqHyo+I+rS+ZJNXgzF8xFMw46rgUykiE9zYxrQnzAhnOqXbqwZA93Ma2U8ayTR4HqYM="
