# don't use container based infrastructure cause we need sudo
sudo: required
language: java
os:
  - linux
jdk:
  - openjdk8
python:
  - "2.7"
cache:
  directories:
  - $HOME/.m2
  - ./node_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
before_install:
  - export CXX=g++-4.9
  - export NODE_OPTIONS=--max-old-space-size=4096
  - export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.pl.project13.maven.git=WARN
  - sudo rm -vf /etc/apt/sources.list.d/*riak*
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update -qq
  - sudo apt-get install cf-cli -y
  - sudo apt-get -y install python-pip python-dev
  - pip install urllib3[secure] --user -I
  - pip install robotframework --user
  - pip install robotframework-extendedselenium2library --user
  - pip install pyyaml --user
  - pip install six --user
# turn off travis default mvn install call and install a recent node version instead
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 10.8.0
  - npm install -g bower
  - npm install -g grunt-cli
# do not install into local maven repo to avoid polluting the cache
script:
  - ./deploy/build-and-deploy.sh unused $CI_DEPLOY_USERNAME $CI_DEPLOY_PASSWORD $TRAVIS_BRANCH $COVERALLS_TOKEN
notifications:
  email:
    recipients:
      - secure: "Rf1Buy3jin0Ge66oyBsjGH6HuW111g9kjt5miW4aSi6Y5jZH5z8E27nDvZrxspMq4oW3j2pvbR1ru/+lEqPmgdtXQs5UxmiSBwMoEQXhMMrZNKzBHgK9MaEMrlx6dXBpwPYhsMqL+ojKmGDgG+X6M9D9SQ/FNQFbTTZWco1YUMlzBUG+eG5iAqsLmJMIn1R3n1VnaOaU5uqdonKfIkmI3uq7vF89oqWvlrHGmXrmahuOie0RwLiyb1cN0pskhszUMe7rmIw+sljS5Ic3JcxgPVWh1Ii5+jdt7GpaMgybMIB5lGQjs9jfftP2QllBqZlAMQLAGmuG44lxgB9AnFdszJqi3NurV+vJG97a9NSWNirKY2Emsb05lqYFeHDE38kqbfyfRX2g2JojdhEymOJoiYRToCFmv2uDvYMslNgpp9BEkQk3xse90uZZ2ropSdwPFMIR4yLhLOaQVl8dmCmtwCun6vEVdmU3GcO82nRuYedkE8midlWbkig6o3lvyaiHTcyk5E9sD6ETTlgxIVnJSLSwKEPi5cVrpU5yXox2duoJVTvxA/MUudtZV3r9Yrar0cT/25FF40RnxR59yWNel/NjR7mLcvWAEQ5g8EAU5mSAWIAjlQr7hZt1dBPQTKA3M2D6LfpSI04vKcf6vXy1mscPHI0Nu6Otti98SzXt5us="
