# don't use container based infrastructure cause we need sudo
sudo: required
language: java
os:
  - linux
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - ./node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update -qq
  - sudo apt-get install cf-cli -y
# turn off travis default mvn install call and install a recent node version instead
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 8.1.4
  - npm install -g bower
  - npm install -g grunt-cli
# do not install into local maven repo to avoid polluting the cache
script:
  - mvn -Pdev --settings ./buildconfig/settings.xml -B -DrepoToken=$COVERALLS_TOKEN package
  - cf login -u $CI_DEPLOY_USERNAME -p $CI_DEPLOY_PASSWORD -o DZHW -s dev -a https://api.run.pivotal.io
  - cf push -f ./deploy/manifest-dev.yml
  - ./node_modules/protractor/bin/webdriver-manager update --standalone
  - ./node_modules/protractor/bin/protractor ./src/test/protractor/protractor.conf.js
after_script:
 - mvn coveralls:report
notifications:
  email:
    recipients:
      - secure: "ou3vhKwxHLnmGCmbEYDdr1MiWYA3hurcJ9jFV+b+nstc4C1v2Gd+tGp/mzXc7yYmPI6bcGegrM9wDnRqjhCpWQly6ECY4xUeTE1nyyw3wm9VzcJSG6Po9L6JBY40i/cUbhU6qi8bEiFU4Aah3eA4dlmtuQpCYJqftfrfG8LS4INe6Q9snNnyRa9GXcDOluELvhVGg+NWdKHZuPdAVfQ/JxIGpebzhdw0Vf47+NYjsPUsgoa/qZ9H8AJlcyW8G2Hw2cw6dDiWO1nrvnoiQFaNCGCevXzAIJ11EngHU9bj+Bke5Qyjac4yycwtovYOAF7jZGygyS+zCRqxDRplB8ZlzTNTA0CWxD77xNC5mDkrM/XlT2uqjlTm3FIrUT/jtYvbgIHnBY7uNuYis3Kk9bnqic34n/b4EhM444c9kKl0pqh8FR1RxPUscFM3a1+2hlJe0fAkTUjZFokDMVqEjqBnNxanzX1j+AMJBMCwf5ySl8I64urzwpvVtVhTYIcDCfdDpOoPszC8vP+Vy+TgUGtj73WamL+eEOf0rqoDa2g6b3wFIv+wvBjaPWhR5sxy1G1StTdHPjxxNEUKhPFKgmj4TCiGVmNErL6SLXn/wtYUxS1ygZwNb41bA9DERKs6CNaLyt1pL+SpipXMyjK2SFEzsYExJRnFu0X8KrV4XUNqXWA="
      - secure: "pefQxn5iw167UfSblujLIkUCZ7DwxUzzAnzZ6ZeNUquiWwYnHEpUWVWWAqZx+e3Ut1q5Q3hSJ5kdWR//exXVN24Xrtx+ctMQe15Q+G9SWqV7Mh5L5Jw11OGolxVUqSgUW5ea7rxk2BdfFJxVJLiGZW+KdAIDa9C/QZDNFrloRwo6PkKLDoMFk9EySSvA+09Uj/MmyM8udj0Xsx4XRKvPrFUO984Sb3iXloYezZ0qaB8tsqt8Jnl4Df251WN/Fuzlu4ZupVLNT3cM7bbGiBGSrEduhrtLipRP/wfr8n6IPqHTfLufSo5GuKOJbtVOLKSIfXCQKFtEWt8TIicWZ1wW5QnxeSUg2+P2/dv00NIXRMRpuAGEdg4YUOlhVY6ldQzuilpxdDMwqz/qek0OH9/dIOzaEZUTioXYz6nFFOgn6bxa95PzlzKjnY6tHMx8XZDSz1Q7iJ8cmYsWAjvVehRvWI2yAuIZp6BeuUZ9iyx6kTo/NBCZlpi62SvrDeKZIpyD1RP+CyXKRfP4xE69Rqfhdf+pVAAmyIG8uT1RFWPfciCQO8XiHjxUdtCjBea1J1i1GEL2mVfkZivAwu4BfJSdWMOK/Vj+0/zNrKYn0vDMvR3+qOzLkW5ftjOj5v6VqrqXKDHjalj40JpIY3K7dZfnoDKZZCQ0ZpUR0/trp+KFGfQ="
