# don't use container based infrastructure cause we need sudo
sudo: required
language: java
os:
  - linux
jdk:
  - openjdk8
python:
  - "2.7"
cache:
  directories:
  - $HOME/.m2
  - ./node_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
stages:
    - name: build
      if: NOT (branch =~ /^saikotitis.*$/ || branch =~ /^(development|master|test)$/)
    - name: build and deploy
      if: branch =~ /^(development|master|test)$/
    - name: e2e smoketests
      if: type = cron || branch =~ /^saikotitis.*$/
    - name: nightly e2e tests publicuser
      if: type = cron || branch =~ /^saikotitis.*$/
    - name: nightly e2e tests dataprovider
      if: type = cron || branch =~ /^saikotitis.*$/
    - name: nightly e2e tests publisher
      if: type = cron || branch =~ /^saikotitis.*$/
jobs:
  include:
    - stage: build
      name: "Client & Server Build"
      install:
        - export CXX=g++-4.9
        - export NODE_OPTIONS=--max-old-space-size=4096
        - export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.pl.project13.maven.git=WARN
        - sudo apt-get -y install python-pip python-dev --allow-unauthenticated
        - pip install git+https://github.com/dzhw/javasphinx.git --user
        - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 11.6.0
        - npm install -g bower
        - npm install -g grunt-cli
      script:
        - ./deploy/build.sh unused $TRAVIS_BRANCH $COVERALLS_TOKEN
    - stage: build and deploy
      name: "Build and Deploy to PWS"
      install:
        - export CXX=g++-4.9
        - export NODE_OPTIONS=--max-old-space-size=4096
        - export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.pl.project13.maven.git=WARN
        - sudo apt-get -y install python-pip python-dev --allow-unauthenticated
        - pip install git+https://github.com/dzhw/javasphinx.git --user
        - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 11.6.0
        - npm install -g bower
        - npm install -g grunt-cli
        - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        - echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        - sudo apt-get update -qq
        - sudo apt-get install cf-cli -y --allow-unauthenticated
        - sudo netstat -pelnut
      script:
        - ./deploy/build-and-deploy.sh unused $CI_DEPLOY_USERNAME $CI_DEPLOY_PASSWORD $TRAVIS_BRANCH $COVERALLS_TOKEN $TRAVIS_EVENT_TYPE
    - stage: e2e smoketests
      name: "Chrome Smoketest"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs -v USE_SAUCELABS:TRUE -v BROWSER:chrome --include smoketest --exclude firefoxonly ./src/test/robotframework
    - name: "Firefox Smoketest"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs -v USE_SAUCELABS:TRUE -v BROWSER:firefox --include smoketest --exclude chromeonly ./src/test/robotframework
    - name: "Edge Smoketest"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs -v USE_SAUCELABS:TRUE -v BROWSER:edge --include smoketest --exclude firefoxonly --exclude chromeonly --exclude noslowpoke ./src/test/robotframework
    - name: "IE11 Smoketest"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs -v USE_SAUCELABS:TRUE -v BROWSER:ie --include smoketest --exclude firefoxonly --exclude chromeonly --exclude noslowpoke ./src/test/robotframework
    - stage: nightly e2e tests publicuser
      name: "Nightly Chrome Tests (Public User)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/chrome -v USE_SAUCELABS:TRUE -v BROWSER:chrome --include publicuserNOTsmoketestNOTfirefoxonlyNOTlocalonly ./src/test/robotframework
    - name: "Nightly Firefox Tests (Public User)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/firefox -v USE_SAUCELABS:TRUE -v BROWSER:firefox --include publicuserNOTsmoketestNOTchromeonlyNOTlocalonly ./src/test/robotframework
    - name: "Nightly IE11 Tests (Public User)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/ie11 -v USE_SAUCELABS:TRUE -v BROWSER:ie --include publicuserNOTsmoketestNOTfirefoxonlyNOTchromeonlyNOTlocalonly ./src/test/robotframework
    - name: "Nightly Edge Tests (Public User)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/edge -v USE_SAUCELABS:TRUE -v BROWSER:edge --include publicuserNOTsmoketestNOTfirefoxonlyNOTchromeonlyNOTnoslowpokeNOTlocalonly ./src/test/robotframework
    - stage: nightly e2e tests dataprovider
      name: "Nightly Chrome Tests (Dataprovider)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/chrome -v USE_SAUCELABS:TRUE -v BROWSER:chrome --include dataproviderNOTsmoketestNOTfirefoxonlyNOTlocalonly ./src/test/robotframework
    - name: "Nightly Firefox Tests (Dataprovider)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/firefox -v USE_SAUCELABS:TRUE -v BROWSER:firefox --include dataproviderNOTsmoketestNOTchromeonlyNOTlocalonly ./src/test/robotframework
    - name: "Nightly IE11 Tests (Dataprovider)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/ie11 -v USE_SAUCELABS:TRUE -v BROWSER:ie --include dataproviderNOTsmoketestNOTfirefoxonlyNOTchromeonlyNOTlocalonly ./src/test/robotframework
    - name: "Nightly Edge Tests (Dataprovider)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/edge -v USE_SAUCELABS:TRUE -v BROWSER:edge --include dataproviderNOTsmoketestNOTfirefoxonlyNOTchromeonlyNOTnoslowpokeNOTlocalonly ./src/test/robotframework
    - stage: nightly e2e tests publisher
      name: "Nightly Chrome Tests (Publisher)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/chrome -v USE_SAUCELABS:TRUE -v BROWSER:chrome --include publisherNOTsmoketestNOTfirefoxonlyNOTlocalonly ./src/test/robotframework
    - name: "Nightly Firefox Tests (Publisher)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/firefox -v USE_SAUCELABS:TRUE -v BROWSER:firefox --include publisherNOTsmoketestNOTchromeonlyNOTlocalonly ./src/test/robotframework
    - name: "Nightly IE11 Tests (Publisher)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/ie11 -v USE_SAUCELABS:TRUE -v BROWSER:ie --include publisherNOTsmoketestNOTfirefoxonlyNOTchromeonlyNOTlocalonly ./src/test/robotframework
    - name: "Nightly Edge Tests (Publisher)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/edge -v USE_SAUCELABS:TRUE -v BROWSER:edge --include publisherNOTsmoketestNOTfirefoxonlyNOTchromeonlyNOTnoslowpokeNOTlocalonly ./src/test/robotframework
notifications:
  email:
    recipients:
      - secure: "Rf1Buy3jin0Ge66oyBsjGH6HuW111g9kjt5miW4aSi6Y5jZH5z8E27nDvZrxspMq4oW3j2pvbR1ru/+lEqPmgdtXQs5UxmiSBwMoEQXhMMrZNKzBHgK9MaEMrlx6dXBpwPYhsMqL+ojKmGDgG+X6M9D9SQ/FNQFbTTZWco1YUMlzBUG+eG5iAqsLmJMIn1R3n1VnaOaU5uqdonKfIkmI3uq7vF89oqWvlrHGmXrmahuOie0RwLiyb1cN0pskhszUMe7rmIw+sljS5Ic3JcxgPVWh1Ii5+jdt7GpaMgybMIB5lGQjs9jfftP2QllBqZlAMQLAGmuG44lxgB9AnFdszJqi3NurV+vJG97a9NSWNirKY2Emsb05lqYFeHDE38kqbfyfRX2g2JojdhEymOJoiYRToCFmv2uDvYMslNgpp9BEkQk3xse90uZZ2ropSdwPFMIR4yLhLOaQVl8dmCmtwCun6vEVdmU3GcO82nRuYedkE8midlWbkig6o3lvyaiHTcyk5E9sD6ETTlgxIVnJSLSwKEPi5cVrpU5yXox2duoJVTvxA/MUudtZV3r9Yrar0cT/25FF40RnxR59yWNel/NjR7mLcvWAEQ5g8EAU5mSAWIAjlQr7hZt1dBPQTKA3M2D6LfpSI04vKcf6vXy1mscPHI0Nu6Otti98SzXt5us="
      - secure: "qs+bz5OoLMCyft0Y0MCLfsoOpR8fhCovHOY4a9ScRG0xYQPh2Yita9TZsf5UGApTbLSyl03D5yRwDZtrKFq5a4rBKRYHhvrL3gWB3LzMCSp0sDlmrWAyUrbMoCyiRUEA+/aYbUeUaT7V2u1eVQPszJY2NMhctra3+vLzzpUliTJK515Wc1S+0RJhS3Ycekmjuj0QEdpScsIHiyLOB5RGgwuw6Pu6voKTid7JV2US+Zc5Sgkge6sPn4RqVqghhyE76NWst8frjboFlTj0CSk7nyS7cjAebkb6a5lcbW7bmhRMJeiZk5k+kJL9OQagyy9gkXSVoPmIm5psjEo2nAjgNgWT2DBYUxO8BoFQUqCN/Uf6MKZ8O/nTinWNmhsDmahFNt+QMoikKEc0BCOIQWrEsWi7dENCmRzwl0IUOClkHWAdin4OHPH4/PLBWTcWfBblFXcLbMtKQ99zQ4cD6qA+UOFj5lyvb3wMQO1Eonr5nIp18H4JiiXdRnnIc6Yim35JH5/8SNHWeqXsXOHR+1i0Ji55geMVPbeQh20OgLzySYxphLg+sQkbavb4N/Q6Y9MbziHfK+nEqic66IFwRkacVQYIf7HHdtJPw3eIms+hs+Abapir775MaE6Mzjs3Ni/+PH8NdKm6GSpgtmDqGg5LtvR/Q0oyp6PGrQrhmDQGk28="
      - secure: "kwKI7uXpTNpgajPSBooDz+JQ+LEn3QZuHnlAZGsl75cRaLcq3iuqeeqgbpUtlT7fvVMSNY0Vv8O+N/+5mr5k18YTvhXWyg+SBLKyXijSQqyi4fglSIpHAbwHR+O51kRyJ/ZpKLVbwLhylp3aXcG2+QyGvqTpEA8LyBYvTeZ5ho0pwn6knUvsWCYdtb5Tl6zydLo0IMtZo72yAHPMYPXhk6J7TBagiCShOZyRnViD9V7DjbtrJG+KyXiP9zcbp6oGCN7X2WLX1tOdeafoZ0jAulHGtcMZpN3DuN0G2DSUOmweLZ2bQVw6vIEBfFQ0ZS6BsQiOb8qKvn3d3xKv96tFe/uC1bn9jGD1k/MPfz3pLWo6f9eAQcg3ELQb+uDpaazSiXgbDiH26pOfURCPtSJfyDSQUAlK+wnM+LGc3YNgQiX37X1QsdLtFHqosGnxCtj+6807SeoZjcFnJHmxHgv8jiw6dw/YAwwOSPJbhdBn9Mjpq5/9f0IuyKXmyLO+EHul168IqOg0ZfmtNauiaA/+QN4824gFombPdJTdQysgLDSabw9m0ozu6iAqD5xP0dx9wbM/WSJmMP59evP4/SxKCMaUHfkYL8ONd41kovmP71Aop0IfPMtk8ERGvB4tfQSslGVhvquT3lSWqsz+hB19ROJ1SnI9LhUj7pnVklHewt8="
      - secure: "gaEeUFxqw4BnxSW/V+wpV+pPA1Iyr2M0p5Gmz2OryzclKcosE2iA2qNfI1o9XLmQTQ3W7wR5xq7Ezzrh8LqwvRU/H7YPkHRnTXa12RgWfJ7YNgcv9ULDGStwgeJpo5FxyjxNaZJEFwl5RqrNTrqtIJqqKK6IXqd8PqG3w9g/A8v1SQbca7yrVMPrXX+tKxYH4fgr//sJtEmRQe+CKZCeky5Cwr8+n1CI1TcD4XzzQe5VprXCzV+16+y+9Lkp9ujG7EEVm0XZoFqy2CqEWMOFBMU58ENpAcFLqp1HiP0AEVB7uk7tH+pFXdYNnzJ1PQj+kormKzjsfFb0zeQaD/vrMPuufQJ6OFPc7+hxLfz5lUYtIRM1RNTHDhrJJWaU9ma9ISuBwffh20qymtQ1VGp1pB7CUQFJK+zejKejVOPOoAL0BqlYMKW21KgZuhqMHaDVOiE3oDc01dF1Mn03xKPoYX0Wr0OZUvPXzHUU0jeJnqa6YdFZhnK1Vv13Hkw9NOMMD0B46Ub2sjZJnIDttvOTtDIlttZIVMrc+QCH3ivNzocUaYFJ+lpUy7AuZxiBgtIiEZdSBC0FPMuiMhrij3ZnJ8CVEJvHUCd7/1d7VvWn+um95E5G2rp0Riln2okudkzddZjyvTEao0W3010p+bxvnDX8j27co0oUf7VSDTUb5lU="
