# don't use container based infrastructure cause we need sudo
sudo: required
language: java
os:
  - linux
jdk:
  - openjdk8
python:
  - "2.7"
cache:
  directories:
  - $HOME/.m2
  - ./node_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
stages:
    - name: build
      if: NOT (branch =~ /^saikotitis.*$/ || branch =~ /^(development|master)$/)
    - name: build and deploy
      if: branch =~ /^(development|master)$/
    - name: e2e smoketests
      if: branch = development || branch =~ /^saikotitis.*$/
    - name: nightly e2e tests publicuser
      if: branch = development || branch =~ /^saikotitis.*$/
    - name: nightly e2e tests dataprovider
      if: branch = development || branch =~ /^saikotitis.*$/
    - name: nightly e2e tests publisher
      if: branch = development || branch =~ /^saikotitis.*$/
jobs:
  include:
    - stage: build
      name: "Client & Server Build"
      install:
        - export CXX=g++-4.9
        - export NODE_OPTIONS=--max-old-space-size=4096
        - export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.pl.project13.maven.git=WARN
        - sudo apt-get -y install python-pip python-dev --allow-unauthenticated
        - pip install git+https://github.com/dzhw/javasphinx.git --user
        - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 11.6.0
        - npm install -g bower
        - npm install -g grunt-cli
      script:
        - ./deploy/build.sh unused $TRAVIS_BRANCH $COVERALLS_TOKEN
    - stage: build and deploy
      name: "Build and Deploy to PWS"
      install:
        - export CXX=g++-4.9
        - export NODE_OPTIONS=--max-old-space-size=4096
        - export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.pl.project13.maven.git=WARN
        - sudo apt-get -y install python-pip python-dev --allow-unauthenticated
        - pip install git+https://github.com/dzhw/javasphinx.git --user
        - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 11.6.0
        - npm install -g bower
        - npm install -g grunt-cli
        - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        - echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        - sudo apt-get update -qq
        - sudo apt-get install cf-cli -y --allow-unauthenticated
        - sudo netstat -pelnut
      script:
        - ./deploy/build-and-deploy.sh unused $CI_DEPLOY_USERNAME $CI_DEPLOY_PASSWORD $TRAVIS_BRANCH $COVERALLS_TOKEN $TRAVIS_EVENT_TYPE
    - stage: e2e smoketests
      name: "Chrome Smoketest"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs -v USE_SAUCELABS:TRUE -v BROWSER:chrome --include smoketest --exclude firefoxonly ./src/test/robotframework
    - name: "Firefox Smoketest"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs -v USE_SAUCELABS:TRUE -v BROWSER:firefox --include smoketest --exclude chromeonly ./src/test/robotframework
    - name: "Edge Smoketest"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs -v USE_SAUCELABS:TRUE -v BROWSER:edge --include smoketest --exclude firefoxonly --exclude chromeonly --exclude noslowpoke ./src/test/robotframework
    - name: "IE11 Smoketest"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs -v USE_SAUCELABS:TRUE -v BROWSER:ie --include smoketest --exclude firefoxonly --exclude chromeonly --exclude noslowpoke ./src/test/robotframework
    - stage: nightly e2e tests publicuser
      name: "Nightly Chrome Tests (Public User)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/chrome -v USE_SAUCELABS:TRUE -v BROWSER:chrome --include publicuserNOTsmoketestNOTfirefoxonly ./src/test/robotframework
    - name: "Nightly Firefox Tests (Public User)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/firefox -v USE_SAUCELABS:TRUE -v BROWSER:firefox --include publicuserNOTsmoketestNOTchromeonly ./src/test/robotframework
    - name: "Nightly IE11 Tests (Public User)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/ie11 -v USE_SAUCELABS:TRUE -v BROWSER:ie --include publicuserNOTsmoketestNOTfirefoxonlyNOTchromeonly ./src/test/robotframework
    - name: "Nightly Edge Tests (Public User)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/edge -v USE_SAUCELABS:TRUE -v BROWSER:edge --include publicuserNOTsmoketestNOTfirefoxonlyNOTchromeonlyNOTnoslowpoke ./src/test/robotframework
    - stage: nightly e2e tests dataprovider
      name: "Nightly Chrome Tests (Dataprovider)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/chrome -v USE_SAUCELABS:TRUE -v BROWSER:chrome --include dataproviderNOTsmoketestNOTfirefoxonly ./src/test/robotframework
    - name: "Nightly Firefox Tests (Dataprovider)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/firefox -v USE_SAUCELABS:TRUE -v BROWSER:firefox --include dataproviderNOTsmoketestNOTchromeonly ./src/test/robotframework
    - name: "Nightly IE11 Tests (Dataprovider)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/ie11 -v USE_SAUCELABS:TRUE -v BROWSER:ie --include dataproviderNOTsmoketestNOTfirefoxonlyNOTchromeonly ./src/test/robotframework
    - name: "Nightly Edge Tests (Dataprovider)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/edge -v USE_SAUCELABS:TRUE -v BROWSER:edge --include dataproviderNOTsmoketestNOTfirefoxonlyNOTchromeonlyNOTnoslowpoke ./src/test/robotframework
    - stage: nightly e2e tests publisher
      name: "Nightly Chrome Tests (Publisher)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/chrome -v USE_SAUCELABS:TRUE -v BROWSER:chrome --include publisherNOTsmoketestNOTfirefoxonly ./src/test/robotframework
    - name: "Nightly Firefox Tests (Publisher)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/firefox -v USE_SAUCELABS:TRUE -v BROWSER:firefox --include publisherNOTsmoketestNOTchromeonly ./src/test/robotframework
    - name: "Nightly IE11 Tests (Publisher)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/ie11 -v USE_SAUCELABS:TRUE -v BROWSER:ie --include publisherNOTsmoketestNOTfirefoxonlyNOTchromeonly ./src/test/robotframework
    - name: "Nightly Edge Tests (Publisher)"
      install:
        - ./src/test/robotframework/setup.sh
      script:
        - export PYTHONWARNINGS="ignore"
        - travis_wait 50 robot -P ./src/test/robotframework/libs -d target/test/robotframework/logs/edge -v USE_SAUCELABS:TRUE -v BROWSER:edge --include publisherNOTsmoketestNOTfirefoxonlyNOTchromeonlyNOTnoslowpoke ./src/test/robotframework
notifications:
  email:
    recipients:
      - secure: "Rf1Buy3jin0Ge66oyBsjGH6HuW111g9kjt5miW4aSi6Y5jZH5z8E27nDvZrxspMq4oW3j2pvbR1ru/+lEqPmgdtXQs5UxmiSBwMoEQXhMMrZNKzBHgK9MaEMrlx6dXBpwPYhsMqL+ojKmGDgG+X6M9D9SQ/FNQFbTTZWco1YUMlzBUG+eG5iAqsLmJMIn1R3n1VnaOaU5uqdonKfIkmI3uq7vF89oqWvlrHGmXrmahuOie0RwLiyb1cN0pskhszUMe7rmIw+sljS5Ic3JcxgPVWh1Ii5+jdt7GpaMgybMIB5lGQjs9jfftP2QllBqZlAMQLAGmuG44lxgB9AnFdszJqi3NurV+vJG97a9NSWNirKY2Emsb05lqYFeHDE38kqbfyfRX2g2JojdhEymOJoiYRToCFmv2uDvYMslNgpp9BEkQk3xse90uZZ2ropSdwPFMIR4yLhLOaQVl8dmCmtwCun6vEVdmU3GcO82nRuYedkE8midlWbkig6o3lvyaiHTcyk5E9sD6ETTlgxIVnJSLSwKEPi5cVrpU5yXox2duoJVTvxA/MUudtZV3r9Yrar0cT/25FF40RnxR59yWNel/NjR7mLcvWAEQ5g8EAU5mSAWIAjlQr7hZt1dBPQTKA3M2D6LfpSI04vKcf6vXy1mscPHI0Nu6Otti98SzXt5us="
      -  secure: "qs+bz5OoLMCyft0Y0MCLfsoOpR8fhCovHOY4a9ScRG0xYQPh2Yita9TZsf5UGApTbLSyl03D5yRwDZtrKFq5a4rBKRYHhvrL3gWB3LzMCSp0sDlmrWAyUrbMoCyiRUEA+/aYbUeUaT7V2u1eVQPszJY2NMhctra3+vLzzpUliTJK515Wc1S+0RJhS3Ycekmjuj0QEdpScsIHiyLOB5RGgwuw6Pu6voKTid7JV2US+Zc5Sgkge6sPn4RqVqghhyE76NWst8frjboFlTj0CSk7nyS7cjAebkb6a5lcbW7bmhRMJeiZk5k+kJL9OQagyy9gkXSVoPmIm5psjEo2nAjgNgWT2DBYUxO8BoFQUqCN/Uf6MKZ8O/nTinWNmhsDmahFNt+QMoikKEc0BCOIQWrEsWi7dENCmRzwl0IUOClkHWAdin4OHPH4/PLBWTcWfBblFXcLbMtKQ99zQ4cD6qA+UOFj5lyvb3wMQO1Eonr5nIp18H4JiiXdRnnIc6Yim35JH5/8SNHWeqXsXOHR+1i0Ji55geMVPbeQh20OgLzySYxphLg+sQkbavb4N/Q6Y9MbziHfK+nEqic66IFwRkacVQYIf7HHdtJPw3eIms+hs+Abapir775MaE6Mzjs3Ni/+PH8NdKm6GSpgtmDqGg5LtvR/Q0oyp6PGrQrhmDQGk28="
      - secure: "D83NkvSGh6e6hy1ZA+cMHxrcSpcdQn35+HQYSmBPT78p42/8PAhTfExOuV9yCQNo9/Qw0MqOCkhNRI48u1h8zYCdKLypXmttdeOC853o7jvfLl4iRBdUhzBmoKy51DAPiiUdMVC3WevZdKyGmsE+fVjXaB9vtocgk7Dswhq1SbR1Q5ZJPURNKvR4CFxa1z6NRy6uxy7EbeFzQlJJMhYf1wd6OmFTOWm/sBy7yAkySQhc12eIVQml8SSoZj9vH2dd7VTQ8wLI9WMlluBCvTeS7CqcOLEO1Sbgqesn7vYDSL2hqoiQslT6LT98bKK5CVpQWD/2vg+TubppjWfL8jc6fm5FU8BQSIb0CThG2/ZiLWt2DvL9OwzNy6SWz4eVIhhCKbF1QIHNBU3HoZ4BdLNJCrv4HX65kKdF7TcyySYyn9XKkqF5Jdg/ikqOH6i42rucOlv2AYrLeqA9x1hKt2m/3xyIu5EJ8XUjSdgYX33Y0I0ug2jUY9rh8l7i3WoIS4x/0doaOkWigxZXByVXp2ogAirAq2lUV2iXy2qksROp9Bwl9IrRqdU19bzDO+Iz5xrKIwjvGngmrkWPAgP1M/r/MITtvWjwtkBpcI4hn6nhJTgEE5tq9iWQmQUuIjSJ8axV8fTgB1mFJYmMiU6F4BG38YRsO3bJqZi5omzBC30Qptw="
      - secure: "S6YRlQGSxFuP6mtWLWjklvxmfKTCRFhofRqKqwyM4sGD8BmgzQSyDP2Wv7mphRt99JSqlNdiKozrl0Vvnr6BIhJxiF85pH5toy6zzWFo1NaiUgyg+ZvnySx8XVOF9SB1sWBnt22F1U8fIc2atHyVAGbO5jzWTKQSZ4o6qrK4p52ydODwNwkfYGXRKgE2RZm4WbRLMyfH2DJG8u2B1doPX9SmFIt0dGIYHCtZ62CmD4Gdz+bmLNAURitXGLsUjlsnSWzLhcVLuCQTXb4SE+LrXgcSr1lumHONJq3PXbUdEKmNLfWi/sUdD2TWkbKc5YnHBmYsEq9m3veem/idbyg66KvfRMWpnuXbT2+A2NEfgVAeyv2elqPPtOCHq+LgNFWvgSpiElOSkKVf1bw52CKkNH7ZhgN6wUgaRr24Wd4x2uAdOBAIedRHpYVudSgZBZrqiOZ33nAZP3mqt+poEzAOCuzLnpbYSr0k2naRsn9cfvIpqdRYj0fJmi32hCgMIP3YcmJ1TOG1RnyGGTdapqeDjNKjnqIJxQ96BUgEAaKJljRPhrVJDwWjVBjkQuezMgBkChRINTPQoDaq/aPeL1twU13SumNbqpjlzsnp1O3ufKrMGtmMx1ZLMxth+dIzWUEeGQ9OuLTRc/0need2YKf8IT9X9HcMP+vgX4kFkO8HPpU="
