#set the minimum of query ngrams which have to match
search.minimum-should-match-ngrams: 100%

info:
  #set some properties by maven filter
  app.version: "@project.version@"
  app.buildtime: "@buildtime@"
  springboot.version: "@project.parent.version@"
  elasticsearch.version: "@elasticsearch.version@"
  git.commit.id: "@git.commit.id@"
  git.commit.user: "@git.commit.user.name@"
  git.commit.message: "@git.commit.message.short@"
  git.commit.time: "@git.commit.time@"
  
spring:
  data:
    elasticsearch:
      #set the clustername for production
      cluster-name: metadatamanagement
      properties:
        node.local: false
        node.data: true
        http.enabled: false
        discovery.zen.master_election.filter_client: false
        path.data: elasticsearch/data
  #set base name for message sources
  messages:
    basename: i18n/messages
  #enable ISO serialization of JSR 310 date time objects
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mvc:
    async:
      #use ten seconds as request timeout
      request-timeout: 10000
  git:
    properties: git.properties
      
#enable specific actuator endpoints
endpoints:
  enabled: false
  env:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
  configprops:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
  mappings:
    enabled: true
    sensitive: false
    
#enable gzip compression
server:
  compression:
    enabled: true
    
#redirect endpoints     
management: 
     context-path: /admin