# ===================================================================
# Spring Boot configuration for the "local" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    devtools:
        restart:
            enabled: true
            additional-exclude: scripts/**, bower_components/**, assets/**
        livereload:
            enabled: false # we use Grunt + BrowserSync for livereload
    data:
        mongodb:
            host: localhost
            port: 27017
            database: metadatamanagement
    mail:
        host: localhost
        port: 1025
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false
    resources:
      static-locations:
        - file:src/main/webapp/

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: metadatamanagement@localhost

# ===================================================================
# Properties specific to our application
# ===================================================================

metadatamanagement:
  elasticsearch-client:
    url: http://localhost:9200
    read-timeout: 60000
  elasticsearch-angular-client:
    apiVersion: 5.x
    logLevel: error
    pageSize: 10
  dara:
    endpoint: http://dara-test.gesis.org:8084/dara/api/
