#set the minimum of query ngrams which have to match
search.minimum-should-match-ngrams: 100%

#set version by maven filter
info:
  app.version: '@project.version@'
  app.buildtime: '@buildtime@'
  app.buildtime.format: '@maven.build.timestamp.format@'
  springboot.version: '@project.parent.version@'
  elasticsearch.version: '@elasticsearch.version@'
  java.version: ${java.version}
  java.vendor: ${java.vendor}
  os.arch: ${os.arch}
  os.version: ${os.version}
  git.commit.id: ${git.commit.id}
  git.commit.user: ${git.commit.user.name}
  git.commit.message: ${git.commit.message.short}
  git.commit.time: ${git.commit.time}
  
spring:
  data:
    elasticsearch:
      #set the clustername for production
      cluster-name: metadatamanagement
      properties:
        node.local: false
        node.data: true
        http.enabled: false
        discovery.zen.master_election.filter_client: false
  #set base name for message sources
  messages:
    basename: i18n/messages
  #enable ISO serialization of JSR 310 date time objects
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mvc:
    async:
      #use ten seconds as request timeout
      request-timeout: 10000
  git:
    properties: git.properties
      
#enable detailed health info without authentication
endpoints:
  health:
    sensitive: false
    
#enable gzip compression
server:
  compression:
    enabled: true
    
#redirect endpoints     
management: 
     address: metadatamanagement.cfapps.io
     context-path: /admin