# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    data:
      rest:
        base-path: /api
        max-page-size: 50
        default-page-size: 10
        return-body-on-create: false
        return-body-on-update: false
    messages:
        basename: classpath:/i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: HTML
    http:
      encoding:
        force: false
    servlet:
      multipart: 
        max-file-size: 10MB
        max-request-size: 15MB
        
logging:
  level:
    root: warn
    eu.dzhw.fdz.metadatamanagement: info

server:
    port: 8080
    tomcat:
        remote-ip-header: x-forwarded-for
        protocol-header: x-forwarded-proto
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json

management:
  cloudfoundry:
    skip-ssl-validation: true
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - info
        - health
        - configprops
        - metrics
        - httptrace
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
      
javers:
  algorithm: levenshtein_distance
 
# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    mail:
        from: fdz@dzhw.eu
    security:
        authentication:
            oauth:
                clientid: metadatamanagementapp
                secret: $2a$04$1M3yLuQsTu2dJGl0Rj60c.d9dLt1hHpRNMLzilziLM50VgGJ52ckG
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 31
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: false
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: metadatamanagement
