# ===================================================================
# Spring Boot configuration for the "test" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    data:
        mongodb:
            uri: ${vcap.services.mongodb.credentials.uri}
    mail:
        host: ${vcap.services.email.credentials.hostname}
        port: 587
        username: ${vcap.services.email.credentials.username}
        password: ${vcap.services.email.credentials.password}
    thymeleaf:
        cache: true

# ===================================================================
# Properties specific to our application
# ===================================================================

metadatamanagement:
  server:
    instance-index: ${cf.instance.index}
  elasticsearch-client:
    url: ${vcap.services.elasticsearch.credentials.sslUri}
    read-timeout: 60000
  elasticsearch-angular-client:
    apiVersion: '6.2'
    logLevel: error
    pageSize: 10
  dara:
    endpoint: ${vcap.services.dara.credentials.endpoint}
    username: ${vcap.services.dara.credentials.username}
    password: ${vcap.services.dara.credentials.password}
  rabbitmq:
    uri: ${vcap.services.rabbitmq.credentials.uri}
  websockets:
    allowed-origins:
      - https://metadatamanagement-test.cfapps.io
