---
# this is the cloudfoundry manifest for the prod system
applications:
- name: metadatamanagement
  path: ../target/metadatamanagement-prod.war
  memory: 1536M
  disk_quota: 1024M
  instances: 2
  buildpacks:
  - https://github.com/cloudfoundry/java-buildpack
  env:
    SPRING_PROFILES_ACTIVE: prod
    JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{ enabled: false }'
    JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { version: 11.+}}'
    JAVA_OPTS: '-Xss256k -XX:+UseG1GC -XX:+UseStringDeduplication'
  services:
  - mongodb
  - elastic
  - email
  - dara
  - rabbitmq
  - metrics-forwarder-prod
  timeout: 180
  health-check-type: http
  health-check-http-endpoint: /management/info
  routes:
  - route: metadata.fdz.dzhw.eu
  - route: www.metadata.fdz.dzhw.eu
  - route: metadatamanagement.cfapps.io
