---
# this is the cloudfoundry manifest for the dev system
applications:
- name: metadatamanagement
  path: ((path-to-app))
  memory: 2048M
  disk_quota: 1024M
  instances: 3
  buildpacks:
  - https://github.com/cloudfoundry/java-buildpack
  env:
    SPRING_PROFILES_ACTIVE: test
    JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{ enabled: false }'
    JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { version: 11.+}}'
    JAVA_OPTS: '-Xss256k -XX:+UseG1GC -XX:+UseStringDeduplication'
  services:
  - mongodb
  - elastic
  - email
  - dara
  - rabbitmq
  - cloudfoundry
  timeout: 180
  health-check-type: http
  health-check-http-endpoint: /management/info
  routes:
  - route: metadatamanagement-test.cfapps.io
