---
# this is the cloudfoundry manifest for the dev system
applications:
- name: metadatamanagement
  path: ../target/metadatamanagement-test.war
  memory: 1024M
  disk_quota: 1024M
  instances: 3
  buildpacks:
  - https://github.com/cloudfoundry/java-buildpack#v4.16.1
  env:
    SPRING_PROFILES_ACTIVE: test
    JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{ enabled: false }'
  services:
  - mongodb
  - elastic
  - email
  - dara
  - rabbitmq
  - metrics-forwarder-test
  timeout: 180
  health-check-type: http
  health-check-http-endpoint: /management/info
  routes:
  - route: metadatamanagement-test.cfapps.io
